package com.instantsystem.newsly.designsystem.resources.color

import androidx.compose.ui.graphics.Color

val newsly_light_primary = Color(0xFF005AC1)
val newsly_light_onPrimary = Color(0xFFFFFFFF)
val newsly_light_primaryContainer = Color(0xFFD8E2FF)
val newsly_light_onPrimaryContainer = Color(0xFF001A41)
val newsly_light_secondary = Color(0xFF006D3B)
val newsly_light_onSecondary = Color(0xFFFFFFFF)
val newsly_light_secondaryContainer = Color(0xFF66FEA2)
val newsly_light_onSecondaryContainer = Color(0xFF00210E)
val newsly_light_tertiary = Color(0xFFAC3400)
val newsly_light_onTertiary = Color(0xFFFFFFFF)
val newsly_light_tertiaryContainer = Color(0xFFFFDBD0)
val newsly_light_onTertiaryContainer = Color(0xFF390B00)
val newsly_light_error = Color(0xFFBA1A1A)
val newsly_light_errorContainer = Color(0xFFFFDAD6)
val newsly_light_onError = Color(0xFFFFFFFF)
val newsly_light_onErrorContainer = Color(0xFF410002)
val newsly_light_background = Color(0xFFFEFBFF)
val newsly_light_onBackground = Color(0xFF171B23)
val newsly_light_surface = Color(0xFFFEFBFF)
val newsly_light_onSurface = Color(0xFF171B23)
val newsly_light_surfaceVariant = Color(0xFFE1E2EC)
val newsly_light_onSurfaceVariant = Color(0xFF44474F)
val newsly_light_outline = Color(0x81000000)
val newsly_light_inverseOnSurface = Color(0xFFF2F0F4)
val newsly_light_inverseSurface = Color(0xFF303033)
val newsly_light_inversePrimary = Color(0xFFADC6FF)
val newsly_light_shadow = Color(0xFF000000)
val newsly_light_surfaceTint = Color(0xFF005AC1)
val newsly_light_surfaceTintColor = Color(0xFF005AC1)

val newsly_dark_primary = Color(0xFFADC6FF)
val newsly_dark_onPrimary = Color(0xFF002E69)
val newsly_dark_primaryContainer = Color(0xFF004494)
val newsly_dark_onPrimaryContainer = Color(0xFFD8E2FF)
val newsly_dark_secondary = Color(0xFF43E188)
val newsly_dark_onSecondary = Color(0xFF00391C)
val newsly_dark_secondaryContainer = Color(0xFF00522B)
val newsly_dark_onSecondaryContainer = Color(0xFF66FEA2)
val newsly_dark_tertiary = Color(0xFFFFB59D)
val newsly_dark_onTertiary = Color(0xFF5D1800)
val newsly_dark_tertiaryContainer = Color(0xFF842600)
val newsly_dark_onTertiaryContainer = Color(0xFFFFDBD0)
val newsly_dark_error = Color(0xFFFFB4AB)
val newsly_dark_errorContainer = Color(0xFF93000A)
val newsly_dark_onError = Color(0xFF690005)
val newsly_dark_onErrorContainer = Color(0xFFFFDAD6)
val newsly_dark_background = Color(0xFF171B23)
val newsly_dark_onBackground = Color(0xFFE3E2E6)
val newsly_dark_surface = Color(0xFF171B23)
val newsly_dark_onSurface = Color(0xFFE3E2E6)
val newsly_dark_surfaceVariant = Color(0xFF44474F)
val newsly_dark_onSurfaceVariant = Color(0xFFC4C6D0)
val newsly_dark_outline = Color(0x1FFFFFFF)
val newsly_dark_inverseOnSurface = Color(0xFF171B23)
val newsly_dark_inverseSurface = Color(0xFFE3E2E6)
val newsly_dark_inversePrimary = Color(0xFF005AC1)
val newsly_dark_shadow = Color(0xFF000000)
val newsly_dark_surfaceTint = Color(0xFFADC6FF)
val newsly_dark_surfaceTintColor = Color(0xFFADC6FF)

val seed = Color(0xFF4285F4)

val newsly_secondary50 = Color(0xFF00894B)
val newsly_secondary80 = Color(0xFF43E188)

val pinkLight = Color(0xFFD81B60)
val pinkDark = Color(0xFFF48FB1)

val redLight = Color(0xFFD32F2F)
val redDark = Color(0xFFE57373)

val blueLight = Color(0xFF4285F4)
val blueDark = Color(0xFF6DB6FF)

val tealLight = Color(0xFF009688)
val tealDark = Color(0xFF80CBC4)

val indigoLight = Color(0xFF3F51B5)
val indigoDark = Color(0xFF7986CB)

val greenLight = Color(0xFF37BD71)
val greenDark = Color(0xFF7CFCB3)

val limeLight = Color(0xFFCDDC39)
val limeDark = Color(0xFFdce775)

val yellowLight = Color(0xFFffeb3b)
val yellowDark = Color(0xFFfff59d)

val amberLight = Color(0xFFffc107)
val amberDark = Color(0xFFffe082)

val orangeLight = Color(0xFFF86734)
val orangeDark = Color(0xFFFFAC8D)

val brownLight = Color(0xFF795548)
val brownDark = Color(0xFFbcaaa4)

val grayLight = Color(0xFF616161)
val grayDark = Color(0xFFEEEEEE)
